version: '3.4'

services:
  hungrygame:
    image: ${DOCKER_REGISTRY-}hungrygame
    build:
      context: .
      dockerfile: HungryGame/Dockerfile
    environment:
      - SeqServer=http://seq
    networks:
      - jaegernet

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "8888:80"
    volumes:
      - /datadrive:/data
    environment:
      - ACCEPT_EULA=Y

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ~/source/repos/HungryGame/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    ports:
      - 9090:9090
    networks:
      - jaegernet
  

  grafana:
    image: grafana/grafana:latest
    volumes:
     - ~/source/repos/HungryGame/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
     - grafana_data:/var/lib/grafana 
    ports:
     - 3001:3000
    links:
      - prometheus
    networks:
      - jaegernet

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaegernet
    depends_on:
      - hungrygame

networks:
  jaegernet:
  
volumes:
  grafana_data:
  prometheus_data: